# Generated by Django 3.2.16 on 2022-10-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripHistory',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('place', models.CharField(max_length=30)),
                ('starting_time', models.TimeField()),
                ('ending_time', models.TimeField()),
                ('total_cost', models.IntegerField()),
            ],
            options={
                'db_table': 'trip_history',
            },
        ),
    ]
