# Generated by Django 3.2.16 on 2022-10-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleRide',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('driver_id', models.IntegerField()),
                ('place', models.CharField(max_length=20)),
                ('starting_time', models.TimeField()),
                ('ending_time', models.TimeField()),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'schedule_ride',
            },
        ),
    ]
