# Generated by Django 3.2.16 on 2022-11-06 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user_id',
        ),
    ]
