# Generated by Django 3.2.16 on 2022-10-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
